/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InstantJNI */

#ifndef _Included_InstantJNI
#define _Included_InstantJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InstantJNI
 * Method:    Init
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_InstantJNI_Init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     InstantJNI
 * Method:    Function1
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_InstantJNI_Function1
  (JNIEnv *, jobject, jint);

/*
 * Class:     InstantJNI
 * Method:    Function2
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_InstantJNI_Function2
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     InstantJNI
 * Method:    Function3
 * Signature: ([F)F
 */
JNIEXPORT jfloat JNICALL Java_InstantJNI_Function3
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     InstantJNI
 * Method:    Function4
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_InstantJNI_Function4
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     InstantJNI
 * Method:    Function5
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_InstantJNI_Function5
  (JNIEnv *, jobject);

/*
 * Class:     InstantJNI
 * Method:    SwitchColor
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_InstantJNI_SwitchColor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
