/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ExampleJNI */

#ifndef _Included_ExampleJNI
#define _Included_ExampleJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ExampleJNI
 * Method:    function1
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ExampleJNI_function1
  (JNIEnv *, jobject, jint);

/*
 * Class:     ExampleJNI
 * Method:    function2
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ExampleJNI_function2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ExampleJNI
 * Method:    switchColor
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_ExampleJNI_switchColor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
